### PR TITLE
Add reboot functionality

### PR DESCRIPTION
**Pull request by jdaviscooke**
Sometimes when working with a managed-servers environment, it is useful to be able to reboot a managed machine after a provision (due to new software install/configuration, etc)  Using a script to do this on the machine as part of a provisioner doesn't work as the loss of network connectivity will kill the provisioner. 

This pull requests implements the 'vagrant reboot' command, as well as the reboot_server action to accomplish this. Basically, we issue a reboot command over the communicator, then wait for the communicator to report the machine as down, then wait for it to be ready again.

### CODE REVIEW

**Comment by tknerr** [comment]
Hey @jdaviscooke that looks very very nice!

Does this kick in on `vagrant reload` or would you have to say `vagrant reboot`?

I thinkt reusing the existing "reload" action would semantically fit. What do you think?

**Comment by jdaviscooke** [comment]
@tknerr I had originally thought of having this trigger on `vagrant reload`, but after a discussion with some colleagues we decided that it might be too risky, as a reboot is a potentially destructive action, and if someone were to think they were dealing with a normal vagrant box and issue a reload and reboot a server by accident that would be less than ideal. 

That said, if you think it makes more sense to have this trigger on `vagrant reload`, I'm happy to make that change. I would probably have it warn the user that reload in this environment causes the machine to reboot, and require confirmation or a --force flag, if that sounds reasonable?

**Comment by tknerr** [comment]
@jdaviscooke I believe that might stem from the earlier days of vagrant where it was VirtualBox only. Nowadays there are many vagrant-* cloud providers which also use `reload` to reboot an instance. It would also be more consistent within vagrant-managed-servers in terms of reusing existing commands rather than introducing new ones (thin of `up` and `destroy`). 

For that matter I would prefer to reuse the `reload` command. I would be fine with a warning or `-f` / `--force` flag too.

In the end, whether you call it `reload` or `reboot` doesn't matter if the server does not come up anymore, so it's potentially dangerous anyways ;-) So the `--force` flag would actually be super handy in that case. Like it! :+1: 

Once you have it in let me do a quick test drive and I'll release a new version right away.

**Comment by jdaviscooke** [comment]
@tknerr I didn't know that there were other providers using reload for a reboot. So it now responds to `vagrant reload`
We also discussed the necessity for a prompt/force and decided that while it is potentially a risk, i n the long run it is probably fine to follow conventions of this and other providers. You could easily run a `vagrant provision` on a managed machine which could be far worse than a reboot. 

Take it for a spin and let me know what you think! I tested this on Linux and Windows and had success with both (although Windows takes longer as WinRM takes some time to come back online after a reboot)

**Comment by tknerr** [comment]
Works flawless, thanks for the contribution! :+1:  

Release is on the way...

**Pull request merged**
